### PR TITLE
Fix: Update Trainee Dashboard

### LINKED ISSUE #466: Trainee dashboard
# Description

Implement the updated Figma design of the applicant dashboard 

When a trainee has no performance data, empty graphics should not be displayed on their dashboard, a customized display should be shown on the particular section.

### PR DESCRIPTION
**Pull request by kanu-cast**
# PR Description

Fixing trainee dashboard with conditional rendering when there are no performance ratings yet.

# Description of tasks that were expected to be completed

When trainee has no ratings , the dashboard display empty metrics with 2-D graphics that made no sense.
Replacing the empty metrics with a clear 'no rating yet' message 

# Number of Commits

1 commit

# Screenshots (If appropriate)
image

# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Review by rwemakevin — APPROVED** [review]

**Review by elijahladdie — APPROVED** [review]

**Review by aimedivin — APPROVED** [review]

**Review by amiparadis250 — APPROVED** [review]

File: src/pages/TraineeDashboard.tsx [hunk 1]
```diff
@@ -118,6 +158,8 @@ function SupAdDashboard() {
   }
 
   useEffect(() => {
+    const now = new Date(Date.now())
+    console.log('thiis is raw',data)
```
Comment (aimedivin) [inline src/pages/TraineeDashboard.tsx:162]: @kanu-cast remove this console.log()

**Review by aimedivin — COMMENTED** [review]
@kanu-cast , fix the text color for this combobox while them for page is in dark mode

File: src/pages/TraineeDashboard.tsx (hunk 1 above)
Comment (aimedivin) [inline src/pages/TraineeDashboard.tsx]: @kanu-cast remove this console.log()

**Review by aimedivin — CHANGES_REQUESTED** [review]
@kanu-cast , fix the text color for this combobox while them for page is in dark mode

Screenshot from 2024-10-31 23-28-23

File: src/pages/TraineeDashboard.tsx [hunk 2]
```diff
@@ -291,217 +338,331 @@ function SupAdDashboard() {
...
-                      <h1>Good</h1>
-                    ) : (
-                      <h1>Need to improve</h1>
-                    )}
-                  </p>
+              
+              <div className="flex justify-end">
+                <div className='float-right rounded-[40px] border px-3 py-1 text-sm'>Period: 
+                  <div className=" relative inline ml-3">
+                    <select
```
Comment (aimedivin) [inline src/pages/TraineeDashboard.tsx]: @kanu-cast for the above-requested change, apply background-color property for this element it will fix it.

File: src/pages/TraineeDashboard.tsx [hunk 3]
```diff
@@ -291,217 +338,331 @@ function SupAdDashboard() {
...
+                          <div className="h-5 border-2 bg-[#b1b1b1] mx-2" />
+                        </>
+                      ))}
+
+                    </div>
+                    {norating ? "": 
+                      <div className="flex justify-end">
+                        <div className='float-right rounded-[40px] border px-3 py-1 text-sm'>Filter: 
+                          <div className=" relative inline ml-3">
+                            <select
```
Comment (aimedivin) [inline src/pages/TraineeDashboard.tsx]: @kanu-cast same here, apply different background-color property for this element on both dark and light mode it will fix it.

**Review by aimedivin — CHANGES_REQUESTED** [review]

**Review by aimedivin — APPROVED** [review]

**Review by aimedivin — CHANGES_REQUESTED** [review]
@kanu-cast , the filters for page content aren't functioning correctly, performance score isn’t updating based on the selected time range, and the data displayed in the performance sprint table doesn’t match the chosen time, kindly fix that as soon as possible .

**Review by igorihimbazwe — APPROVED** [review]

**Review by elijahladdie — APPROVED** [review]

**Review by aimedivin — APPROVED** [review]
