### PR TITLE
fix app translations

### LINKED ISSUE #167: Translations
App is not properly translated. 

image

After login, the welcome message is displayed in English.

The placeholder should be `...devpulse.co` It was `...pulse.com` before we got our own domain name.
image

image

### PR DESCRIPTION
**Pull request by alaintresor**
# PR Description

Fix #167 issue

# Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you or that you assigned yourself. Make sure you check evey completed task.

# How has this been tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Number of Commits

The number of commits should not exceed **2 commits**. In case they are more than that, please take your time and squash them.

# Screenshots (If appropriate)

# Please check this Checklist before you submit your PR:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-169.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Julienish14 — APPROVED** [review]

**Review by Placide123 — APPROVED** [review]

**Review by alicepretty — APPROVED** [review]

**Review by elissaihimbazwe — APPROVED** [review]

**Review by ishimweeli — APPROVED** [review]

File: src/components/ButtonLoading.tsx [hunk 1]
```diff
@@ -1,16 +1,20 @@
...
-    </button>
-  </div>
-);
+const ButtonLoading: React.FC<Props> = ({ style }) => {
+  const { t } = useTranslation();
+  return (
+    <div className={`flex btn w-fit py-1 px-3 bg-primary font-bold ${style}`}>
+      <div className="loader mr-1" />
+      <button className="ml-1 text-white font-bold" disabled>
+        {t('Processing...')}
```
Comment (ceelogre) [inline src/components/ButtonLoading.tsx:14]: Processing word does not make sense here. Something like `signing you in` is more relatable.

**Review by ceelogre — CHANGES_REQUESTED** [review]

**Review by ceelogre — APPROVED** [review]
