### PR TITLE
fix dashboard redirect

### LINKED ISSUE #175: Dashboard redirect
# Description
Currently, our dashboard is not functional. Let's turn it into a `coming soon` page and redirect loggedin users to `/dashboard/trainees`

### PR DESCRIPTION
**Pull request by elissaihimbazwe**
# PR Description

This PR redirects the user to the dashboard/trainees after logging in and also makes the dashboard a coming soon 

# Description of tasks that were expected to be completed

1. Redirect the user to the dashboard/trainees after logging in the app
2. Make a dashboard a coming soon

# How has this been tested?
1. Login using this link, 👉🏼 [https://devpulse-review-app-183.herokuapp.com/](url)
2. After login You will be redirected to the dashboard/trainees 
3. After try to go to the /dashboard you will find a coming soon page

# Number of Commits

2 commit

# Screenshots (If appropriate)
N/A
# Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code generate no warnings
- [x] My test coverage meet the set test coverage threshold
- [x] There are no vulnerabilities
- [x] There are no conflicts with the base branch

### CODE REVIEW

**Comment by elissaihimbazwe** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-183.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by Placide123 — APPROVED** [review]

**Review by alicepretty — APPROVED** [review]

**Review by Himbaza123h — APPROVED** [review]

File: src/pages/Organization/AdminLogin.tsx [hunk 1]
```diff
@@ -49,9 +49,10 @@ function AdminLogin() {
           await client.resetStore();
           toast.success(t(`Welcome`));
           if (state) {
-            navigate(`${state}`);
-          } else {
-            navigate('/dashboard/');
+            //navigate to ${state},in case you want to make it default (/dashboard),  
+            {data.loginUser.user.role === 'manager' || 'user'? navigate(`/dashboard`): navigate('/dashboard/trainees')}
```
Comment (ceelogre) [inline src/pages/Organization/AdminLogin.tsx]: Why are we redirecting `manager`  and `user` role to dashboard?

**Review by ceelogre — COMMENTED** [review]
Is there any particular reason why admin login does not redirect
image

File: src/pages/Organization/AdminLogin.tsx (hunk 1 above)
Comment (elissaihimbazwe) [reply src/pages/Organization/AdminLogin.tsx]: Because there are no trainees on their dashboard, i chose to remain on the dashboard. do you have any suggestions where we can redirect them

**Comment by elissaihimbazwe** [comment]
> Is there any particular reason why admin login does not redirect image

It's working here, try to check again

**Review by ishimweeli — APPROVED** [review]

**Review by Julienish14 — APPROVED** [review]
