### PR TITLE
Fix Coverage 

### LINKED ISSUE #119: Coverage drop
# Description

Our coverage has dropped below 80% (75% as of this issue). Let's have it increased again.

### PR DESCRIPTION
**Pull request by elissaihimbazwe**
# PR Description
This PR fixes the coverage by increasing it above 80% 

# Description of tasks that were expected to be completed

1. Checking if there are the task which needs to be tested and write the tests
2. Checking open branches if they meet with the coverage needed(no reduction of coverage) if so , write test to increase the coverage
3. Cant' be merged if coverage is below 80%

# How has this been tested?

1. Clone this RP
2. Install needed Depencencies by runing `npm install`
4. Add environment variables check `.env.example` if needed
5. After run `npm run coverage` 

# Number of Commits
1
# Screenshots (If appropriate)
N/A

# Please check this Checklist before you submit your PR:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My code generate no warnings
- [ ] My test coverage meet the set test coverage threshold
- [ ] There are no vulnerabilities
- [ ] There are no conflicts with the base branch

### CODE REVIEW

**Comment by Procech20** [comment]
I deployed a review app for you to try out this pull request 👇🏽
Heroku App: https://devpulse-review-app-136.herokuapp.com/


<hidden purpose="for-rewritable-pr-comment-action-use" value="Deploy"></hidden>

**Review by alicepretty — APPROVED** [review]

**Review by alaintresor — APPROVED** [review]

**Review by Julienish14 — APPROVED** [review]

**Review by Francoise02 — APPROVED** [review]

**Review by Placide123 — APPROVED** [review]

File: src/hook/useAuth.tsx [hunk 1]
```diff
@@ -36,11 +40,13 @@ function UserProvider({ children, ...props }: Props) {
       id: data.user?.profile?.id,
     }));
   };
+  /* istanbul ignore next */
   const logout = () => {
     localStorage.removeItem('auth');
     localStorage.removeItem('auth_token');
     setUser(() => ({ name: '', role: 'user', auth: false }));
   };
```
Comment (ceelogre) [inline src/hook/useAuth.tsx:48]: Should not be ignored.

File: src/pages/AdminTraineeDashboard.tsx [hunk 2]
```diff
@@ -48,6 +50,7 @@ const AdminTraineeDashboard = () => {
   const options: any = [];
   const traineeOptions: any = [];
 
+  /* istanbul ignore next */
   const removeTraineeMod = () => {
     let newState = !removeTraineeModel;
     setRemoveTraineeModel(newState);
```
Comment (ceelogre) [inline src/pages/AdminTraineeDashboard.tsx:56]: A lot of lines in the file can be tested.

**Review by ceelogre — CHANGES_REQUESTED** [review]
There was an overuse of the `ignore` rule. Go through the files again and add more tests.

**Review by ceelogre — APPROVED** [review]
